[model]
model_type = "image"
label_vocab_size = 11
vocab_size = 33
pixel_bins = 32
context_length = 784
d_model = 256
num_layers = 8
num_heads = 16
d_ff = 1024
rope_theta = 10000.0
attention_backend = "torch_sdpa"
attention_sdp_backend = "auto"
device = "cuda"
dtype = "float16"
mask_token_id = 32
null_label_id = 10
use_rope_2d = false
image_height = 28
image_width = 28

[checkpoint]
ckpt_path = "/home/tadhiel/transformerlm/runs/2026-02-05_17-34-14/versions/v006000/model.safetensors"

[inference]
label = 2
num_samples = 16
steps = 784
block_length = 784
temperature = 0.6
top_p = 1.0
cfg_scale = 2.0
remasking = "random"
seed = 123
output_dir = "./runs/2026-02-05_17-34-14/infer_images/6000"
