[optimizer.muon.hidden]
initial_learning_rate = 0.01 # unused in cosine scheduler
max_learning_rate = 0.018
min_learning_rate = 0.0018
momentum = 0.92
weight_decay = 0.01

[optimizer.muon.head]
initial_learning_rate = 0.003 # unused in cosine scheduler
max_learning_rate = 0.0035
min_learning_rate = 0.00035
betas = [0.9, 0.95]
eps = 1e-10
weight_decay = 0.02

[optimizer.muon.embed]
initial_learning_rate = 0.01 # unused in cosine scheduler
max_learning_rate = 0.026
min_learning_rate = 0.0026
betas = [0.9, 0.95]
eps = 1e-10
weight_decay = 0.01

[optimizer.muon.scalar]
initial_learning_rate = 0.0008 # unused in cosine scheduler
max_learning_rate = 0.0009
min_learning_rate = 0.00009
betas = [0.9, 0.95]
eps = 1e-10
weight_decay = 0.02